apiVersion: v1
kind: ResourceQuota
metadata:
  name: http-app-quota
  namespace: ourcoolnamespace
spec:
  hard:
    pods: "10"
    requests.cpu: "3"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 3Gi
